mongodb:
  container_name: postman_mongo
  image: mongo
  ports:
    - 27017:27017
server:
 container_name: postman_node
 image: node
 volumes:
   - ./server:/app/server
 working_dir: /app/server
 command: npm run start
 environment:
   PORT: 3030
 ports:
   - 3030:3030
   - 1923:1923
 links:
   - mongodb
client:
 container_name: postman_client
 image: node
 volumes:
   - ./client:/app/client
 working_dir: /app/client
 command: npm run build
nginx:
  build: ./nginx
  working_dir: /app/client
  ports:
    - 8081:80
    - 1924:1924
  volumes:
   - ./client:/app/client
  links:
    - server:server