mongodb:
  container_name: postman_mongo
  image: mongo
  ports:
    - 27017:27017
server:
 container_name: postman_node
 image: node
 volumes:
   - ./server:/app/server
 working_dir: /app/server
 command: npm run start
 ports:
   - 3030:3000
   - 1923:1923
 links:
   - mongodb
