mongodb:
  image: mongo
  ports:
    - 27017:27017
server:
 image: node
 volumes:
   - ../server:/app/server
 working_dir: /app/server
 command: npm run start
 ports:
   - 3000:3000
 links:
   - mongodb